

export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_FIRST_SUCCESS = 'FETCH_FIRST_SUCCESS';
export const FETCH_SECOND_SUCCESS = 'SECOND_CALL_SUCCESS';
export const FETCH_FUFILLED = 'FETCH_FUFILLED'
export const FETCH_FAILED = 'FETCH_FAILED'
export const FETCH_MERGE_CALL_FUFILLED = 'FETCH_MERGE_CALL_FUFILLED'


export const CONCATMAP_CALL = 'CONCATMAP_CALL'
export const CONCATMAP_CALL_FUFILLED = 'CONCATMAP_CALL_FUFILLED'
export const CONCATMAP_CALL_FUFILLED2 = 'CONCATMAP_CALL_FUFILLED2'


export const FETCH_MERGE_CALL = 'FETCH_MERGE_CALL'

export const  FETCH_FIRST_LOADING_START = 'FETCH_FIRST_LOADING_START'
export const FETCH_SECOND_LOADING_START = 'FETCH_SECOND_LOADING_START'


//ADD_TODO
export const ADD_TODO = 'ADD_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const REMOVE_TODOS = 'REMOVE_TODOS'
export const REMOVE_TODO = 'REMOVE_TODO'
export const GET_TODO_SIZE = 'GET_TODO_SIZE'
